# acronymes.py

# acronymes.py

ACRONYMES = {
    "AC": "Administration centrale",
    "AEPE": "Accompagnants éducatifs petite enfance",
    "AESH": "Accompagnant des Élèves en Situation de Handicap",
    "ALD": "Affection longue durée",
    "AMI": "Amiens",
    "APE": "Association de Parents d'Élèves",
    "APF": "Association des Paralysés de France",
    "APL": "Aide Personnalisée au Logement",
    "ARE": "Allocation de retour à l'emploi",
    "ASH": "Adaptation Scolaire et Scolarisation des élèves Handicapés",
    "ASSR": "Attestation Scolaire de Sécurité Routière",
    "ATP": "Affectation à titre provisoire",
    "ATSEM": "Agent Territorial Spécialisé des Écoles Maternelles",
    "AUC": "Aucun (dans la colonne caractère)",
    "AXM": "Aix-Marseille",
    "BEP": "Brevet d'Études Professionnelles",
    "BES": "Besançon",
    "BOE": "Bénéficiaire de l'obligation d'emploi",
    "BOR": "Bordeaux",
    "BP": "Brevet professionnel",
    "BTS": "Brevet de Technicien Supérieur",
    "BVS": "Bureau vie scolaire ?",
    "CA": "Conseil d'administration",
    "CAER": "Concours d'accès à l'échelle de rémunération (certifié ou agrégé dans l'enseignement privé sous contrat)",
    "CAF": "Caisse d'allocations familiales",
    "CAMSP": "Centre d’Action Médico-Sociale Précoce",
    "CAP": "Certificat d'Aptitude Professionnelle",
    "CAPEPS": "Certificat d'Aptitude au Professorat d'Éducation Physique et Sportive",
    "CASNAV": "Centre Académique pour la Scolarisation des Nouveaux Arrivants et des enfants du Voyage",
    "CASU": "Conseiller d'administration scolaire et universitaire",
    "CCPD": "IEN-Conseil et Coordination Pédagogique Départementale",
    "CD": "Conseil de discipline",
    "CDD": "Contrat à Durée Déterminée",
    "CDI": "Contrat à Durée Indéterminée",
    "CE": "Chef d'établissement",
    "CET": "Compte épargne temps",
    "CFA": "Centre de Formation des Apprentis",
    "CGV": "Conditions générales de vente",
    "CIDJ": "Centre d’Information et de Documentation pour la Jeunesse",
    "CIGEM": "Corps interministériel à gestion ministérielle",
    "CIO": "Centre d'information et d'orientation",
    "CLD": "Congé longue durée",
    "CLE": "Clermont-Ferrand",
    "CLM": "Congé longue maladie",
    "CM": "Congé maladie",
    "CMD": "Conseil médical départemental",
    "CMO": "Congé maladie ordinaire",
    "CMS": "Conseil médical supérieur",
    "CND": "CNED",
    "CNDAC": "CNED",
    "CNDDAC": "CNED",
    "CNDI": "CNED",
    "CNDLI": "CNED",
    "CNDLY": "CNED",
    "CNDPO": "CNED",
    "CNDRE": "CNED",
    "CNDVA": "CNED",
    "CNED": "Centre national d'enseignement à distance",
    "COM": "Collectivité d'outre mer (St-Pierre et Miquelon, Nvelle-Calédonie, Polynésie F, Wallis et Futuna) + Mayotte",
    "COP": "Conseiller d'orientation psychologue",
    "CP": "Cours préparatoire (école élémentaire)",
    "CPAM": "Caisse primaire d'assurance maladie",
    "CPE": "Conseiller Principal d'Éducation",
    "CPF": "Compte personnel de formation",
    "CPGE": "Classe Préparatoire aux Grandes Écoles",
    "CRE": "Créteil",
    "CREPS": "Centre régional d'enseignement physique et sportif",
    "CROUS": "Centre régional des œuvres universitaires et scolaires",
    "CRPE": "Concours régional de professeur des écoles",
    "CVEC": "Contribution à la vie étudiante et de campus",
    "DAASEN": "Directeur académique adjoint des services de l'éducation nationale",
    "DAPP": "Dispositif d'approfondissement du projet professionnel",
    "DASEN": "Directeur académique des services de l'éducation nationale",
    "DBF": "Division budgétaire et financière",
    "DDD": "Défenseur des droits",
    "DDFPT": "Directeur délégué aux formations professionnelles et technologiques",
    "DEC": "Division des examens et concours",
    "DEEP": "Division des… (services des rectorats)",
    "DEP": "Division des… (services des rectorats)",
    "DESEC": "Division des… (services des rectorats)",
    "DEVU": "Division des… (services des rectorats)",
    "DGESCO": "Direction générale de l'enseignement scolaire",
    "DGFIP": "Direction générale des finances publiques",
    "DGH": "Dotation globale horaire",
    "DGRH": "Direction générale des ressources humaines",
    "DIEC": "Division inter des examens et concours",
    "DIJ": "Dijon",
    "DIPE": "Division des personnels (à Versailles)",
    "DIRECCTE": "Direction Régionale des Entreprises, de la Concurrence, de la Consommation, du Travail et de l’Emploi",
    "DIS": "Discrimination",
    "DIVEL": "Division des élèves",
    "DLG": "Lignes directrices de gestion",
    "DNB": "Diplôme national du brevet",
    "DOM": "Départements d'outremer",
    "DOS": "Division de l'organisation scolaire",
    "DPE": "Division des personnels enseignants",
    "DRAJES": "Direction régionale des associations de la jeunesse et des sports",
    "DRAT": "Direction régionale de l'aménagement du territoire",
    "DRFIP": "Direction régionale des finances publiques",
    "DSDEN": "Direction des services de l'éducation nationale",
    "DSE": "Dossier social étudiant",
    "EAF": "Épreuve anticipée de français (en 1ère)",
    "EDT": "Emploi du temps",
    "EMAS": "Equipe mobile académique de sécurité",
    "EN": "Éducation nationale",
    "ENSAP": "Espace Numérique Sécurisé de l’Agent Public",
    "ENT": "Environnement numérique de travail",
    "EPLE": "Établissement public local d'enseignement",
    "EPS": "Éducation Physique et Sportive",
    "ESS": "Économie sociale et solidaire",
    "FPH": "Fonction Publique Hospitalière ?",
    "GLT": "Gestion logique et transports",
    "GRE": "Grenoble",
    "GS": "Grande section (école maternelle)",
    "GUA": "Guadeloupe",
    "GUY": "Guyane",
    "HAN": "Handicap",
    "HAR": "Harcèlement",
    "HPI": "Haut Potentiel Intellectuel",
    "HS": "Heure supplémentaire",
    "IA": "Inspecteur d'académie",
    "IDV": "Indemnité de départ volontaire",
    "IEJ": "Institut d'études judiciaires (école préparant au métier d'avocat)",
    "IEN": "Inspecteur de l'Éducation Nationale",
    "IJ": "Indemnité journalière (en cas de congé de maladie)",
    "IME": "Institut médico éducatif",
    "INE": "Identifiant numérique étudiant",
    "INM": "Indice net majoré",
    "INSERM": "Institut national de la recherche médicale",
    "INT": "International",
    "IPR": "Inspecteur pédagogique régional",
    "ITRF": "Ingénieurs et Techniciens de Recherche et de Formation",
    "IUFM": "Institut universitaire de formation des maîtres",
    "IUT": "Institut universitaire de technologie",
    "LAS": "Licence accès santé",
    "LEGT": "Lycée d'enseignement général et technologique",
    "LGT": "Lycée général et techno",
    "LIL": "Lille",
    "LIM": "Limoges",
    "LLCE": "Lettres-langues-culture étrangère",
    "LP": "Lycée professionnel",
    "LV": "Langue vivante",
    "LYO": "Lyon",
    "MA": "Maître auxiliaire",
    "MAR": "Martinique",
    "MDPH": "Maison Départementale des Personnes Handicapées",
    "MEN": "Ministère de l'Éducation Nationale",
    "MGEN": "Mutuelle générale de l'EN",
    "MON": "Montpellier",
    "MS": "Moyenne section (école maternelle)",
    "NAN": "Nantes",
    "NAT": "National (pôle de médiation)",
    "NBI": "Nouvelle bonification indiciaire",
    "NCY": "Nancy-Metz",
    "ND": "Non déterminé",
    "NIC": "Nice",
    "NOR": "Normandie",
    "NSI": "Numérique et sciences de l'ingénieur",
    "NUM": "Numérique (problème lié au numérique)",
    "OM": "Outre mer",
    "ORL": "Orléans-Tours",
    "PAI": "Projet d’Accueil Individualisé",
    "PAP": "Plan d’Accompagnement Personnalisé",
    "PAR": "Paris",
    "PB": "Problème",
    "PCR": "Test",
    "PE": "Professeur des écoles ou initial du médiateur",
    "PF": "Polynésie française",
    "PIAL": "Pôle Inclusif d’Accompagnement Localisé",
    "PLC": "Professeur des lycées et collèges",
    "PLP": "Professeur de lycée professionnel",
    "POI": "Poitiers",
    "PRAG": "Professeur agrégé",
    "PRCE": "Professeur certifié",
    "PS": "Petite section (école maternelle)",
    "PSYEN": "Psy de l'éducation nationale",
    "PV": "Procès verbal",
    "RAFP": "Régime Additionnel de la Fonction Publique",
    "RDV": "Rendez-vous",
    "REI": "Reims",
    "REL": "Relationnel (problème)",
    "REN": "Rennes",
    "REP": "Réseau d'éducation prioritaire",
    "REU": "La Réunion",
    "RH": "Ressources humaines",
    "RNCP": "Recueil national des certifications professionnelles",
    "RQTH": "Reconnaissance de travailleur handicapé",
    "SAAM": "Service de l'administration et de l'action de modernisation",
    "SAIO": "Service académique de l'information et de l'orientation",
    "SAJ": "Service des affaires juridiques",
    "SES": "Sciences économiques et sociales",
    "SESSAD": "Service d’Éducation Spéciale et de Soins À Domicile",
    "SG": "Secrétaire / secrétariat général",
    "SHN": "Sportif de haut niveau",
    "SIEC": "Service interacadémique des examens et concours",
    "SIO": "Service de l'information et de l'orientation",
    "SIUMPPS": "Service Inter-Universitaire de Médecine Préventive et de Promotion de la Santé",
    "SRE": "Service des retraites de l'État",
    "SREN": "Service des retraites de l'éducation nationale",
    "STR": "Strasbourg",
    "TA": "Tribunal administratif",
    "TD": "Travaux dirigés",
    "TG": "Terminale générale",
    "TMM": "Trouver mon master",
    "TOU": "Toulouse",
    "TZR": "Titulaire zone de remplacement",
    "ULIS": "Unité Localisée pour l’Inclusion Scolaire",
    "UNICAEN": "Université de Caen Normandie",
    "VAE": "Validation des acquis de l'expérience",
    "VER": "Versailles",
    "VR": "Vice recteur",
}


# Optionnel: liste des codes/bruits connus (si tu veux les mentionner explicitement)
ACRONYMES_BRUIT = {
    "AAA", "AR", "AU", "BBB", "BBBB", "BIJ", "BK", "CDRH", "CLUG", "COR", "CZABAJ",
    "DJ", "DO", "EE", "EEE", "EIJ", "EM", "ENIIIII", "ET", "FF", "FP", "GA", "GGGG",
    "II", "JJJ", "KKK", "LLL", "LLLL", "LRRR", "MK", "MMM", "NNN", "NNNN", "OU",
    "PC", "PCN", "PPP", "PPPP", "RRRR", "RV", "SAB", "SAE", "SSSS", "TS", "TTT",
    "TTTT", "UUU", "UUUU", "VN", "VVV", "XXX", "XXXX", "YYY", "YYYY", "ZZZ"
}
